-- MySQL Script generated by MySQL Workbench
-- Thu Dec  2 12:31:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema int222_project
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `int222_project` ;

-- -----------------------------------------------------
-- Schema int222_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `int222_project` DEFAULT CHARACTER SET utf8 ;
USE `int222_project` ;

-- -----------------------------------------------------
-- Table `int222_project`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `int222_project`.`users` ;

CREATE TABLE IF NOT EXISTS `int222_project`.`users` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `dob` DATE NOT NULL,
  `address` VARCHAR(300) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `tel` VARCHAR(10) NOT NULL,
  `role` VARCHAR(30) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `deleted` INT NULL DEFAULT 0,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `int222_project`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `int222_project`.`brand` ;

CREATE TABLE IF NOT EXISTS `int222_project`.`brand` (
  `bid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `deleted` INT NULL DEFAULT 0,
  PRIMARY KEY (`bid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `int222_project`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `int222_project`.`category` ;

CREATE TABLE IF NOT EXISTS `int222_project`.`category` (
  `catid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`catid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `int222_project`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `int222_project`.`product` ;

CREATE TABLE IF NOT EXISTS `int222_project`.`product` (
  `pid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `description` VARCHAR(2000) NOT NULL,
  `release_date` DATE NOT NULL,
  `image` VARCHAR(200) NOT NULL,
  `warranty` INT NOT NULL,
  `bid` INT NOT NULL,
  `catid` INT NOT NULL,
  `deleted` INT NULL DEFAULT 0,
  PRIMARY KEY (`pid`),
  INDEX `fk_product_brand1_idx` (`bid` ASC) INVISIBLE,
  INDEX `fk_product_category1_idx` (`catid` ASC) VISIBLE,
  CONSTRAINT `fk_product_brand1`
    FOREIGN KEY (`bid`)
    REFERENCES `int222_project`.`brand` (`bid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`catid`)
    REFERENCES `int222_project`.`category` (`catid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `int222_project`.`color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `int222_project`.`color` ;

CREATE TABLE IF NOT EXISTS `int222_project`.`color` (
  `cid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `code` VARCHAR(7) NOT NULL,
  `deleted` INT NULL DEFAULT 0,
  PRIMARY KEY (`cid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `int222_project`.`productcolor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `int222_project`.`productcolor` ;

CREATE TABLE IF NOT EXISTS `int222_project`.`productcolor` (
  `pid` INT NOT NULL,
  `cid` INT NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`pid`, `cid`),
  INDEX `fk_product_has_color_color1_idx` (`cid` ASC) VISIBLE,
  INDEX `fk_product_has_color_product1_idx` (`pid` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_color_product1`
    FOREIGN KEY (`pid`)
    REFERENCES `int222_project`.`product` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_color_color1`
    FOREIGN KEY (`cid`)
    REFERENCES `int222_project`.`color` (`cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `int222_project`.`coupon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `int222_project`.`coupon` ;

CREATE TABLE IF NOT EXISTS `int222_project`.`coupon` (
  `couponcode` VARCHAR(10) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(200) NULL,
  `expdate` DATE NOT NULL,
  `value` DECIMAL(10,2) NOT NULL,
  `ispercent` INT NOT NULL,
  `maxusage` INT NULL,
  `maxdiscount` DECIMAL(10,2) NULL,
  `minprice` DECIMAL(10,2) NULL,
  PRIMARY KEY (`couponcode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `int222_project`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `int222_project`.`orders` ;

CREATE TABLE IF NOT EXISTS `int222_project`.`orders` (
  `oid` INT NOT NULL AUTO_INCREMENT,
  `totalprice` DECIMAL(10,2) NOT NULL,
  `uid` INT NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `couponcode` VARCHAR(10) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`oid`),
  INDEX `fk_order_user1_idx` (`uid` ASC) VISIBLE,
  INDEX `fk_orders_coupon1_idx` (`couponcode` ASC) VISIBLE,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`uid`)
    REFERENCES `int222_project`.`users` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_coupon1`
    FOREIGN KEY (`couponcode`)
    REFERENCES `int222_project`.`coupon` (`couponcode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `int222_project`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `int222_project`.`review` ;

CREATE TABLE IF NOT EXISTS `int222_project`.`review` (
  `pid` INT NOT NULL,
  `uid` INT NOT NULL,
  `review` VARCHAR(200) NULL,
  `rating` INT NULL,
  `datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`pid`, `uid`),
  INDEX `fk_review_product1_idx` (`pid` ASC) VISIBLE,
  INDEX `fk_review_users1_idx` (`uid` ASC) VISIBLE,
  CONSTRAINT `fk_review_product1`
    FOREIGN KEY (`pid`)
    REFERENCES `int222_project`.`product` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_users1`
    FOREIGN KEY (`uid`)
    REFERENCES `int222_project`.`users` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `int222_project`.`orderdetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `int222_project`.`orderdetail` ;

CREATE TABLE IF NOT EXISTS `int222_project`.`orderdetail` (
  `oid` INT NOT NULL,
  `pid` INT NOT NULL,
  `cid` INT NOT NULL,
  `amount` INT NOT NULL,
  `priceeach` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`oid`, `pid`, `cid`),
  INDEX `fk_product_has_order_order1_idx` (`oid` ASC) VISIBLE,
  INDEX `fk_orderdetail_productcolor1_idx` (`pid` ASC, `cid` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_order_order1`
    FOREIGN KEY (`oid`)
    REFERENCES `int222_project`.`orders` (`oid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderdetail_productcolor1`
    FOREIGN KEY (`pid` , `cid`)
    REFERENCES `int222_project`.`productcolor` (`pid` , `cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
